export const sentences = [
  "The cat purred softly.",
  "Raindrops fell on the roof.",
  "She smiled and waved goodbye.",
  "The river flowed with grace.",
  "Stars twinkled in the night.",
  "He whispered a quiet prayer.",
  "The clock struck twelve midnight.",
  "Leaves rustled in the wind.",
  "The ocean waves crashed gently.",
  "Birds chirped in the morning.",
  "He gazed at the horizon.",
  "Snow covered the silent village.",
  "A butterfly landed on her hand.",
  "The forest echoed with life.",
  "She laughed at the joke.",
  "The sun set behind mountains.",
  "A shadow moved across the room.",
  "Lanterns glowed in the dark.",
  "The breeze was cool tonight.",
  "Children played in the garden.",
  "He picked up the guitar.",
  "Clouds gathered over the hills.",
  "The rain tapped the window.",
  "The phone rang once more.",
  "She sipped her hot tea.",
  "Footsteps approached from the hallway.",
  "The door creaked open slowly.",
  "He watched the candle flicker.",
  "The book fell with a thud.",
  "A song played in the distance.",
  "The wind howled through trees.",
  "The dog barked at strangers.",
  "Lights glimmered across the lake.",
  "They shared a knowing glance.",
  "The stars formed a pattern.",
  "He stood at the gate.",
  "The morning fog was thick.",
  "The fire crackled and roared.",
  "She wore a bright dress.",
  "They whispered among the crowd.",
  "The rain washed the streets.",
  "The city never truly sleeps.",
  "A cat prowled on the fence.",
  "He felt a chill inside.",
  "The painting captured her eyes.",
  "She hummed a familiar tune.",
  "He reached for the sky.",
  "The child giggled with joy.",
  "A plane flew overhead noisily.",
  "He sighed and turned away.",
  "The garden smelled of roses.",
  "The night was perfectly still.",
  "The ship sailed at dawn.",
  "An owl hooted from afar.",
  "The river's current was strong.",
  "The lamp flickered and dimmed.",
  "The flowers bloomed in spring.",
  "The coffee was too bitter.",
  "The path led into shadows.",
  "The trees swayed in unison.",
  "The window was slightly open.",
  "Thunder rumbled in the distance.",
  "A spider crawled up slowly.",
  "She picked up the phone.",
  "The clock ticked rhythmically.",
  "The sunset painted the sky.",
  "They walked in comfortable silence.",
  "His voice was a whisper.",
  "The water rippled with fish.",
  "A car honked loudly nearby.",
  "The park was almost empty.",
  "She glanced at the time.",
  "The mountain stood tall ahead.",
  "The baby slept soundly.",
  "The table was set perfectly.",
  "The boat rocked with waves.",
  "The key clicked into place.",
  "The letter was unreadable.",
  "She brushed her hair gently.",
  "The night breeze was refreshing.",
  "The silence was almost deafening.",
  "The stars were brilliantly clear.",
  "He walked through the snow.",
  "The music played on repeat.",
  "The chair creaked when moved.",
  "The ice cream melted quickly.",
  "The cat meowed for food.",
  "The sun warmed their faces.",
  "The car engine roared loudly.",
  "He finished his last sentence.",
  "The waves splashed the shore.",
  "The movie credits rolled up.",
  "The soup tasted perfectly seasoned.",
  "The wind played with leaves.",
  "The alarm clock buzzed loudly.",
  "The bridge swayed in wind.",
  "The street was eerily quiet.",
  "The cake smelled like heaven.",
  "The book captivated her interest.",
  "The clouds parted revealing stars.",
];
